language: python
sudo: false

services:
  - docker

env:
  global:

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - bash .keep_alive.sh &  # Generate output periodically.
  - pip install jupyter-repo2docker
  - pip list

script:
  - repo2docker . --no-run
