language: python
sudo: false

services:
  - docker

env:
  global:
    - GH_REF: github.com/NSLS-II/scipy-binder.git

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: BUILD_DOCS=true SUBMIT_CODECOV=true NUMPY=1.17

python:
  - 3.7

env:
  - NUMPY=1.17

before_install:
  - |
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-${arch}-x86_64.sh -O miniconda.sh
    chmod +x miniconda.sh
    ./miniconda.sh -b -p ~/mc
    source ~/mc/etc/profile.d/conda.sh
    conda update conda --yes
    export CONDARC=ci/condarc

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - bash .keep_alive.sh &  # Generate output periodically.
  - pip install jupyter-repo2docker
  - pip list

script:
  - repo2docker . --no-run
