#!/bin/bash

jupyter labextension install dask-labextension

# Install extension that supports '%matplotlib widget'.
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib

# Install extension that supports Voilà preview pane.
jupyter labextension install @jupyter-voila/jupyterlab-preview
