#!/bin/bash

git clone --single-branch --branch v0.1.0a26 https://github.com/bluesky/tiled.git /tmp/tiled
git clone --single-branch --branch v2.0.0a10 https://github.com/bluesky/databroker.git /tmp/databroker
pip install '/tmp/tiled[complete]'
pip install '/tmp/databroker[complete]'
